### ISSUE TITLE
require('webpack') does not find webpack

### ISSUE THREAD

**Issue by gbirke** [jmfirth/docker-webpack#3]
strangely, when my `webpack.config.js` contains the line

    const webpack = require('webpack');

node does not find the module. A workaround is to add `-e 'NODE_PATH=/usr/local/lib/node_modules' ` to my docker command, but I'd expect requiring webpack to work out of the box.

Tested with 6 and latest build on my Mac. Maybe some Docker environment variables that are important for the node environment are not set on macOS?

**Comment by jmfirth** [comment]
Webpack is installed globally within the docker container.  Does your package.json have "webpack" as a dependency or devDependency?  If not, you will not be able to require it, and adding it to your package.json and making sure it in your local project's node_modules folder should resolve.

**Comment by gbirke** [comment]
Thank you. I thought that would be unneccessary if webpack is installed globally. Because then I don't understand the benefits/use cases of  a Docker image with webpack preinstalled instead of just using the node Docker image. Could you tell me, I'm really curious.
